### ISSUE TITLE
On babeljs filter I can't use import ?

### ISSUE THREAD

**Issue by nenodias** [amol-/dukpy#11]
Something like

`import Vue from 'vue';`
Or
`import Ember from 'ember';`

**Comment by amol-** [comment]
You can, but you must tell babeljs how they should be transpiled.

For example if you want to manage modules through UMD:

```
src = dukpy.babel_compile(_in.read(), plugins=['transform-es2015-modules-umd'])
```

or if you want to load them through SystemJS:

```
src = dukpy.babel_compile(_in.read(), plugins=['transform-es2015-modules-systemjs'])
```
