### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by dwoz** [amol-/dukpy#18]
I'm curious if anyone knows what (if any) calls to dukpy are thread safe?

From what I have been able to gather so far. The safest bet is to instantiate dukpy.JSInterpreter() for each 'thread/request' in a web app. The downside to this is having to load any library javascript code durring the request.

Is this *not* safe?
```
app = Flask(__name__)
jsi = JSInterpreter()
jsi.evaljs(libs_js)

@app.route('/'):
def index():
      jsi.eval(request_js)
     ...
```

Is this the 'correct' way?
```
app = Flask(__name__)

@app.before_request
def before_request():
      g.jsi = JSInterpreter()
      g.jsi.evaljs(libs_js)

@app.route('/'):
def index():
      g.jsi.eval(request_js)
     ...
```

**Comment by amol-** [comment]
A single interpreter is not thread safe and can't be shared between threads, the memory heap of the interpreter is not thread safe. You can by the way make a different interpreter for each thread. So I guess that using a `threading.local` might be the way to go in case of persistent threads like in case of web applications. Just make sure you properly reset any global variables between requests.
