### ISSUE TITLE
Invalid link in the error warning

### ISSUE THREAD

**Issue by chfw** [amol-/dukpy#30]
Pyecharts user pointed out that the link in the following error message is no longer valid. Could you please see if you could address this issue in your next release?

```
Running setup.py install for dukpy: finished with status 'error'
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
```

Reference:

https://github.com/pyecharts/pyecharts/issues/646

**Comment by amol-** [comment]
Think this is not something we can change, comes from the buildchain itself.

**Comment by chfw** [comment]
Our users found this https://www.scivision.co/python-windows-visual-c++-14-required/ useful too.
