### ISSUE TITLE
Release for Python 3.7

### ISSUE THREAD

**Issue by carsonyl** [amol-/dukpy#31]
Please create a release with wheels for Python 3.7. I've added dukpy as a dependency for my library, [PyPAC](https://github.com/carsonyl/pypac), but I'm holding off on declaring Python 3.7 support until dukpy has wheels for it on PyPI.

And thanks for your work! I really appreciate it.

**Comment by amol-** [comment]
Version 0.2.1 is releasing with Python 3.7 wheel
