### ISSUE TITLE
compile error with python3.7 on mac

### ISSUE THREAD

**Issue by HughesLou** [amol-/dukpy#36]
hi, when I try to insall dukpy with latest version 0.2.2 (or 0.2.1, 0.2.0) on mac, some error messages occur.

Mac: RELEASE_X86_64 x86_64
Python: 3.7
pip3: 18.0

when run command:
`pip3 install dukpy`

error messages:
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -DDUK_OPT_DEEP_C_STACK=1 -DDUK_OPT_NONSTD_REGEXP_DOLLAR_ESCAPE=1 -DDUK_OPT_OCTAL_SUPPORT=1 -I./src/duktape -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/duktape/duktape.c -o build/temp.macosx-10.13-x86_64-3.7/src/duktape/duktape.o
    duk_bi_date_unix.c:53:15: error: array has incomplete element type 'struct tm'
            struct tm tms[2];
                         ^
    duk_bi_date_unix.c:53:9: note: forward declaration of 'struct tm'
            struct tm tms[2];
                   ^
    duk_bi_date_unix.c:134:28: error: invalid application of 'sizeof' to an incomplete type 'struct tm'
            DUK_MEMZERO((void *) tms, sizeof(struct tm) * 2);
                                      ^     ~~~~~~~~~~~
    ./src/duktape/duk_config.h:1965:46: note: expanded from macro 'DUK_MEMZERO'
    #define DUK_MEMZERO(p,n) DUK_MEMSET((p), 0, (n))
                                                 ^
    /usr/include/secure/_string.h:76:33: note: expanded from macro 'memset'
                    __builtin___memset_chk (dest, __VA_ARGS__, __darwin_obsz0 (dest))
                                                  ^~~~~~~~~~~
    duk_bi_date_unix.c:53:9: note: forward declaration of 'struct tm'
            struct tm tms[2];
...

Command "/usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/x0/y4wx_dy95cg6kshhsnnvlhkr0000gn/T/pip-install-nemfkg94/dukpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/x0/y4wx_dy95cg6kshhsnnvlhkr0000gn/T/pip-record-afo8rlwm/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/x0/y4wx_dy95cg6kshhsnnvlhkr0000gn/T/pip-install-nemfkg94/dukpy/

**Comment by webknjaz** [comment]
@amol- I think it might be a good idea to add macOS builds to Travis CI matrix..

**Comment by webknjaz** [comment]
@HughesLou what was the last one not failing?

**Comment by webknjaz** [comment]
Wrong compile time dependency?

**Comment by webknjaz** [comment]
Still, having this in CI won't hurt.

**Comment by amol-** [comment]
I'm not against it, just didn't have time to :D

**Comment by webknjaz** [comment]
Leave it to me. I've got some good experience with various CI stuff :)

**Comment by HughesLou** [comment]
> @HughesLou what was the last one not failing?

I haven't installed dukpy with any previous Python version. it's the first time on my Mac with Python 3.7

**Comment by HughesLou** [comment]
> build/lib.macosx-

OS version is 10.13

running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.13-x86_64-3.7
    creating build/lib.macosx-10.13-x86_64-3.7/dukpy
    copying dukpy/run.py -> build/lib.macosx-10.13-x86_64-3.7/dukpy
    copying dukpy/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/dukpy
    copying dukpy/lessc.py -> build/lib.macosx-10.13-x86_64-3.7/dukpy
    copying dukpy/evaljs.py -> build/lib.macosx-10.13-x86_64-3.7/dukpy
    copying dukpy/babel.py -> build/lib.macosx-10.13-x86_64-3.7/dukpy
    copying dukpy/install.py -> build/lib.macosx-10.13-x86_64-3.7/dukpy
    copying dukpy/coffee.py -> build/lib.macosx-10.13-x86_64-3.7/dukpy

**Comment by amol-** [comment]
@webknjaz Are you still willing to experiment on this? I noticed there were a bunch of reports for people having problems installing dukpy on OSX. Even though I develop on OSX and thus I can confirm it works fine in a properly set environment, I'd say that it would be great to get rid of the problems those users are facing.

**Comment by webknjaz** [comment]
The last part in the puzzle is to ship wheels for macOS users: https://github.com/amol-/dukpy/pull/40#issuecomment-461389162

**Comment by amol-** [comment]
closing as we now provide wheels for OSX

**Comment by BoboTiG** [comment]
Wheels for macOS would be very great indeed 👍 :)

**Comment by webknjaz** [comment]
FWIW with Travis bailing on FOSS it's recommended to migrate to GHA that would also unify the build workflows

**Comment by amol-** [comment]
Wheels for OSX are now provided at release time, see https://github.com/amol-/dukpy/releases/tag/wheels-test
M1 wheels are not yet available but I plan to implement them in the next few weeks

**Comment by webknjaz** [comment]
> M1 wheels are not yet available but I plan to implement them in the next few weeks

I'm hearing that Macstadium can give a free VM for FOSS, wonder if it's hard to plug it into GHA...
