### ISSUE TITLE
Have a duckpy context that lasts for more than more tha one .evaljs() call

### ISSUE THREAD

**Issue by azazel75** [amol-/dukpy#4]
Hi @amol-,  

this is a feature request, not a bug.

As you maybe remember, i'm using duckpy with babeljs to compile ES6+ javascript to ES5 js. 
In this use case, evaluating the babeljs minified source code which is 750 KB  takes time and this slows down the overall per-file translation time. If the number of code blocks (or files) to translate is known this can be resolved with an evaljs() wrapper that handles such multiple blocks.  Unfortunately this doesn't cover all the use cases where it would be nice to have a js interpreter already "hot", waiting for translation job... but let me contextualize a bit.

I'm using duckpy together with [metapensiero.pj (AKA Javascripthon)
](https://github.com/azazel75/metapensiero.pj) to transpile anything  ranging from a tree of Python 3.5 source files to a code object  (a class, a function) to ES6+ JS and then to ES5 with babeljs. 

Having an "hot" duckpy interpreter, with all the babeljs code already loaded would mean that converting and serving  python-ish code to the client becomes possible if the client has loaded the dependencies already.

**Comment by amol-** [comment]
Shouldn't be too hard to achieve by keeping around same execution contest.
Only issue is that if executing your code changes the state of the context, it will be changed forever.

So it might make sense to have it optional.

**Comment by azazel75** [comment]
yes, I agree

**Comment by amol-** [comment]
a516c6b4638da53b980fb30fe618452f67fa76a7 should provide support for this, see https://github.com/amol-/dukpy#using-a-persistent-javascript-interpreter

**Comment by azazel75** [comment]
thank you very much, I'll test it ASAP!
