### ISSUE TITLE
Release for Python 3.8

### ISSUE THREAD

**Issue by carsonyl** [amol-/dukpy#51]
Please create a release with wheels for Python 3.8. Thanks!

**Comment by webknjaz** [comment]
Sending a PR adding 3.8 to the CI and removing 3.4 (because it's EOL) should do the trick.

**Comment by amol-** [comment]
I wanted to make next released with https://github.com/amol-/dukpy/pull/46/files to upgrade duktape, but I haven't yet had a chance to verify it on enough different projects to make sure there isn't any regression. Which made me delay the release, but I guess it might be a good strategy to make a new stable release with just PY3.8 wheel and an alpha one for new branch

**Comment by amol-** [comment]
0.2.3 was released with Python 3.8
