### ISSUE TITLE
Packaged Babel is out of date

### ISSUE THREAD

**Issue by Mortal** [amol-/dukpy#6]
Currently dukpy ships with Babel 6.4.4 minified, which does not include [a fix](https://github.com/babel/babel/pull/3442) for a [particular bug](https://phabricator.babeljs.io/T7198) that I am encountering.

Would it be easy to update dukpy to a newer Babel?

**Comment by amcgregor** [comment]
The copy of Babel built-in appears to be a combined/minified version which includes the external dependencies.  It'd be really, really nice to have the process used to compact Babel in this way exposed to users of the library, as an option, for example, when running `dukpy-install`.

**Comment by amol-** [comment]
BabelJS package is took from https://github.com/Daniel15/babel-standalone/releases 

In some cases fixing regular expressions to escape `{` and `}` as been necessary, but apart from that is usually the prepackaged file.

**Comment by amol-** [comment]
DukPy 0.0.5 comes with babel 6.14
