### ISSUE TITLE
Math.trunc not supported by evaljs

### ISSUE THREAD

**Issue by ypiguet-epfl** [amol-/dukpy#62]
In `dukpy.evaljs`, the math function `Math.trunc` raises the exception `_dukpy.JSRuntimeError: TypeError: undefined not callable`. Other math functions, such as `Math.floor`, work.

To reproduce in Python 3 (tested in 3.6.9):
```
>>> import dukpy
>>> print(dukpy.evaljs("Math.trunc(2.3)"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/.local/lib/python3.6/site-packages/dukpy/evaljs.py", line 134, in evaljs
    return JSInterpreter().evaljs(code, **kwargs)
  File "/home/xxx/.local/lib/python3.6/site-packages/dukpy/evaljs.py", line 57, in evaljs
    res = _dukpy.eval_string(self, jscode, jsvars)
_dukpy.JSRuntimeError: TypeError: undefined not callable
        duk_js_call.c:776
        eval src/pyduktape.c:1 preventsyield
>>> print(dukpy.evaljs("Math.floor(2.3)"))
2
```

**Comment by webknjaz** [comment]
I'd recommend adding PRs with xfailing tests for such cases so there's an acceptance test in the tree whenever somebody gets around to fixing it.

**Comment by webknjaz** [comment]
You must be using some old version. I wrote a test and it succeeds on master.

**Comment by webknjaz** [comment]
https://github.com/amol-/dukpy/pull/63
