### ISSUE TITLE
some emoji not supported

### ISSUE THREAD

**Issue by tsuga** [amol-/dukpy#70]
I'm getting an error when the js code contains a special emoji.

MWE:
`dukpy.evaljs("var data = '💫'; data")`

Error:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 1: invalid continuation byte`

Thank you

**Comment by Aran-Fey** [comment]
I'm also having issues with emojis, though with a different error:

```python
>>> dukpy.evaljs('"\u26a1\ufe0e \ud83d\udca6"')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\dukpy\evaljs.py", line 138, in evaljs
    return JSInterpreter().evaljs(code, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\dukpy\evaljs.py", line 52, in evaljs
    jscode = jscode.encode('utf-8')
             ^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 4-5: surrogates not allowed
```

**Comment by Hamza5** [comment]
Same problem here.
My workaround was to use `emoji.demojize(script)` from the `emoji` library before passing the script to `dukpy`.

**Comment by amol-** [comment]
> Same problem here. My workaround was to use `emoji.demojize(script)` from the `emoji` library before passing the script to `dukpy`.

Have you tried with dukpy 0.4.0 recently released? Is this still an issues?

**Comment by amol-** [comment]
Closing as it seems to work correctly on 0.4.0

```
>>> import dukpy
>>> dukpy.evaljs("var data = '💫'; data")
'💫'
>>> 
```
